repositories:
- name: prometheus-communuity
  url: https://prometheus-community.github.io/helm-charts

- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: kube-prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  disableValidationOnInstall: true

- name: mimir
  namespace: monitoring
  chart: grafana/mimir-distributed
  disableValidationOnInstall: true

- name: loki
  namespace: monitoring
  chart: grafana/loki
  disableValidationOnInstall: true

- name: tempo
  namespace: monitoring
  chart: grafana/tempo
  disableValidationOnInstall: true